name: 'Build'

on:
  push:
    branches: ['**']

jobs:
  test:
    name: 'Run lint and unit tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the test script'
        run: 'npm run test:lint && npm run test'

  bundle:
    name: 'Build package'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the build script'
        run: 'npm run build'
